brew ’aspell’
brew ’autoconf’
brew ’automake’
brew ’babashka’
brew ’bat’
brew ’burl’
brew ’ccls’
brew ’clang-format’
brew ’clj-kondo’
brew ’clojure’
brew ’clojure-lsp’
brew ’ditaa’
brew ’editorconfig’
brew ’exa’
brew ’exiftool’
brew ’fzf’
brew ’git’
brew ’git-fresh’
brew ’git-extras’
brew ’gitleaks’
brew ’grc’
brew ’hr’
brew ’htop’
brew ’hub’
brew ’ispell’
brew ’mcfly’
brew ’nmap’
brew ’ripgrep’
brew ’ripgrep-all’
brew ’rust’
brew ’rust-analyzer’
brew ’sloc’
brew ’starship’
brew ’tmux’
brew ’topgrade’
brew ’trash’
brew ’wtf’
brew ’z’
brew ’zsh’
brew ’zsh-autosuggestions’
brew ’zsh-completions’
brew ’zsh-git-prompt’
brew ’zsh-navigation-tools’
brew ’zsh-syntax-highlighting’
brew ’zydis’
