* ~

This repository contains the lion's share of the configuration-files
that I use on my boxes. It's written in a literate style with
[[https://orgmode.org][org-mode]], so it can be read almost like a book.

[[https://hkjels.github.com/home/][Read it?]]

* Get in touch

If you would like to reach out to me about any of this, you can create
an issue or email me: henrik @ kjerringvag・no

* Up & running

My home relies heavily on Emacs to tangle code-blocks into sourcefiles
that can be installed. Evaluating the line below in your terminal will
install [[https://brew.sh][Homebrew]] and the listed dependencies. The only "dotfiles" that
I keep separate are my editor configurations. I have a set of
configurations for both Vim and Emacs. I no longer use Vim, so their
quite dated, but my Emacs configurations are available for inspiration
at [[https://github.com/hkjels/elan][Elan]].
#+begin_src shell
make install
#+end_src

* Dependencies

#+name: deps
- autoconf
- automake
- bat
- exa
- fzf
- git
- git-fresh
- git-extras
- gitleaks
- grc
- hr
- htop
- hub
- mas
- nmap
- sloc
- starship
- thefuck
- tldr
- tmux
- topgrade
- trash
- tree
- wtf
- z
- zsh
- zsh-autosuggestions
- zsh-completions
- zsh-git-prompt
- zsh-navigation-tools
- zsh-syntax-highlighting
- zydis

#+name: casks
- imageoptim
- numi
- origami-studio
- sketch
- slack
- sourcetrail

#+name: macapps
| 1287239339 | ColorSlurp                    |
|  424390742          | Compressor                    |
| 1482920575 | DuckDuckGo Privacy Essentials |
|  424389933 | Final Cut Pro                 |
|  990588172 | Gestimer                      |
|  419330170 | Moom                          |
| 1289583905 | Pixelmator Pro                |
| 1482454543 | Twitter                       |
|  497799835 | Xcode                         |

#+name: brew
#+begin_src emacs-lisp :var deps=deps
(mapconcat 'identity
	(-map (lambda (dep)
		(message "%s \"%s\"" "brew" (car dep))) deps) "\n")
#+end_src

#+name: cask
#+begin_src emacs-lisp :var deps=casks
(mapconcat 'identity
	(-map (lambda (dep)
		(message "%s \"%s\"" "cask" (car dep))) deps) "\n")
#+end_src

#+name: mas
#+begin_src emacs-lisp :var deps=macapps
(mapconcat 'identity
	   (-map (lambda (dep)
		   (message "%s \"%s\", id: %s" "mas" (car (cdr dep)) (car dep))) deps) "\n")
#+end_src

#+begin_src ruby :tangle Brewfile :noweb yes
tap "homebrew/cask"
tap "borkdude/brew"
#+end_src

Brews are libraries and commandline interfaces.
Often brews are bottled, meaning installation is just about
downloading to a location that's on your ~PATH~.
#+begin_src ruby  :tangle Brewfile :noweb yes :comments org
<<brew()>>
#+end_src

Casks are executables that can not be found in the Appstore.
There are also some resources like fonts available as Casks.
#+begin_src ruby  :tangle Brewfile :noweb yes :comments org
<<cask()>>
#+end_src

With using ~Mas~ we can download applications from the Appstore directly
from the commandline.
#+begin_src ruby  :tangle Brewfile :noweb yes :comments org
<<mas()>>
#+end_src

* Makefile                                                           :noexport:

#+begin_src makefile :tangle Makefile
.PHONY: install bundle

TIC=tic
CURL=curl -fsSL

brew:
	@type -p "$@" >/dev/null 2>&1 || $(CURL) "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"

bundle: brew
	$< $@

.terminfo: terminfo-24bit
	$(TIC) -o "$HOME/$@" $<

install: .terminfo bundle
#+end_src
